background            #00090c
foreground            #ffffff

# black
color0  #00090c
color8  #18afca

# red
color1  #ff2a37
color9  #ff99a2

# green
color2  #c3f9e9
color10 #ffffff

# yellow
color3  #ff4a59
color11 #ffced3

# blue
color4  #887bd3
color12 #efecfa

# magenta
color5  #db89b9
color13 #ffffff

#cyan
color6  #51ded1
color14 #c2f7f2

#white
color7  #ffffff
color15 #ffffff


